### ISSUE TITLE
Envelope Issue in Pokémon Ruby/Sapphire/Emerald

### ISSUE THREAD

**Issue by N6661** [ipatix/agbplay#49] opened 2022-06-27 06:37 UTC
The attack of some notes on PSG ch 1 & 2 in the Ending Theme from Pokémon Ruby/Sapphire/Emerald (song 455 on all three ROMs) are completely missing.

Issue originated in [00f4fe5](https://github.com/ipatix/agbplay/commit/00f4fe5e7a0cf8f42d620d73cecacb125e142f53) and has persisted since.

See attached zip for examples of mGBA output and agbplay output.
[example.zip](https://github.com/ipatix/agbplay/files/8989028/example.zip)

**Comment by N6661** [comment] 2022-06-28 07:24
For what it's worth, [00f4fe5](https://github.com/ipatix/agbplay/commit/00f4fe5e7a0cf8f42d620d73cecacb125e142f53) introduced the above-mentioned attack bug into Pokémon Center from Pokémon Ruby/Sapphire/Emerald (song 400 on all three ROMs) and while the issue in Pokémon Center was fixed in [04cfdb](https://github.com/ipatix/agbplay/commit/04cfdb5d4c1d4fa13b86d85c5975dc28a210b8a4), the same issue in Ending Theme was not. [(Example of the problem in Pokémon Center](https://github.com/ipatix/agbplay/files/8998570/example.zip).

To clarify, neither Ending Theme nor Pokémon Center had the attack bug before [00f4fe5](https://github.com/ipatix/agbplay/commit/00f4fe5e7a0cf8f42d620d73cecacb125e142f53).

It seems that there're still some edge cases in regards to volume calculation that still isn't quite accurate.

**Comment by ipatix** [comment] 2022-06-28 18:05
So would you say the problem in the first example can be described as the tone dropping out even though it should not?

**Comment by N6661** [comment] 2022-06-28 19:49
It may or may not be, idk. That's why I opened a separate issue since #44 existed before [00f4fe5](https://github.com/ipatix/agbplay/commit/00f4fe5e7a0cf8f42d620d73cecacb125e142f53). And yes, I suppose you could call it dropping out in both examples.

**Comment by ipatix** [comment] 2023-09-30 07:29
Can you check if the problem is fixed?

**Comment by N6661** [comment] 2023-09-30 23:08
Unfortunately the issue has not be fixed. Regardless of what `simulate-cgb-sustain-bug` is set to, the error still persists. However, this issue _was_ previously fixed in the [psg_debugging](https://github.com/ipatix/agbplay/tree/psg_debugging) branch which doesn't seem to have been merged into the current master branch. It also means that this issue is a separate issue from #44.

**Comment by N6661** [comment] 2023-10-01 00:46
I did a preliminary test by manually merging the code changes from [psg_debugging](https://github.com/ipatix/agbplay/tree/psg_debugging) with the current master branch and that fixes this issue without undoing the fix for #44. I'll let you have a more thorough look at the code though since I don't know if my janky manual splicing has any unintended consequences. Just letting you know, that seems to be the right direction.

**Comment by ipatix** [comment] 2023-10-01 10:27
Lol, I don't remember this branch at all. I'll have to check what I've done there...

**Comment by ipatix** [comment] 2023-10-01 10:54
Okay, I remember the idea but were always smarter afterwards and I already see edge cases where that fix doesn't work. I'm working on a proper fix right now.

**Comment by ipatix** [comment] 2023-10-01 13:05
Should be fixed now.

**Closed** 2023-10-01 13:05 UTC
